### PR TITLE
Add company users API

### PR DESCRIPTION
**Pull request by pastelInc**
#### Why?
Why are you making this change?

REST API is defined but not implemented.

#### How?
Technical details on your change

Add company users API.

### CODE REVIEW

**Review by jonnyom — APPROVED** [review]
Hey @pastelInc thanks for this! I think this looks good. We can work on bundling this into the next release 👍

**Comment by jonnyom** [comment]
@pastelInc that's merged now. The functionality should all be there now for you 😄 thanks again!

**Comment by pastelInc** [comment]
@jonnyom Thank you for merging! I always use intercom a lot :blush:

**Comment by pastelInc** [comment]
@jonnyom Thank you for merging! I always use intercom a lot :blush:

**Pull request merged**
