### PR TITLE
[NEW] Add Permanent Delete user endpoint

### PR DESCRIPTION
**Pull request by hongmingChm**
Add the ability to Permanently Delete user through API.

### CODE REVIEW

**Comment by choran** [comment]
hi @hongmingChm 
Thanks for the PR, really appreciate it.
I just looked over it, looks good but could you also replace the current delete operations with an [archive](https://github.com/intercom/intercom-php/pull/253/files) method for clarity?

In some of the other SDKs we have added an archive option just to be consistent with the new approach, i.e. archiving a user and permanently deleting one.

So one option is just to create a new archive method which can then be called if anyone is still using the old delete method. That way new users can call archive and older version can still use delete but will also call the same archive method.

Does that make sense?
Thanks again for the PR

**Comment by hongmingChm** [comment]
Hi @choran ,

Thanks for the Code Review :D 

Glad to be able to participate.

Yup. It does make sense. I agree on the second approach on adding a new archive method while supporting the original delete method. Will be working on this.
At the same time, I am thinking to modify the readme to change the delete method to archive method as well so new user will start to use the new archive method instead. And also adding deprecation notice as well.

Thank you so much~

**Comment by hongmingChm** [comment]
@choran 
I've done the code update. xD

Let me know if there are something else need to improve/change~

Thanks again so much for your time.

**Comment by hongmingChm** [comment]
@choran Hi there, any status with the PR? 

Please do let me know if anything I can do to improve the PR further :D 

Thank you so much.

**Comment by choran** [comment]
Hi @hongmingChm thanks for reminding me about this, I will try and review it this week and get back to you 👍

**Pull request closed without merging**
